package com.halalclassified.app.ui.common

data class CategoryOption(
    val label: String,
    val filterValue: String
)

const val AllPakistan = "All Pakistan"

val AnimalCategoryOptions = listOf(
    CategoryOption("Cows", "Cow"),
    CategoryOption("Bulls", "Bull"),
    CategoryOption("Goats", "Goat"),
    CategoryOption("Sheep", "Sheep"),
    CategoryOption("Camels", "Camel"),
    CategoryOption("Buffaloes", "Buffalo")
)

val BreedOptionsByCategory = mapOf(
    "Cows" to listOf("Sahiwal", "Cholistani", "Red Sindhi", "Tharparkar", "Friesian Cross"),
    "Bulls" to listOf("Sahiwal", "Cholistani", "Red Sindhi", "Tharparkar", "Friesian Cross"),
    "Goats" to listOf("Beetal", "Kamori", "Teddy", "Gulabi", "Barbari", "Damani", "Nachi"),
    "Sheep" to listOf("Lohi", "Kajli", "Thalli", "Balkhi", "Damani"),
    "Camels" to listOf("Makrani", "Sindhi", "Bikaneri", "Kharai"),
    "Buffaloes" to listOf("Nili-Ravi", "Kundi", "Azad")
)

val PakistanCities = listOf(
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Faisalabad",
    "Peshawar",
    "Quetta",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Abbottabad",
    "Bahawalpur",
    "Sargodha",
    "Mardan",
    "Mingora",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Gujrat",
    "Sheikhupura",
    "Jhelum",
    "Rahim Yar Khan",
    "Kasur",
    "Okara",
    "Sahiwal",
    "Vehari",
    "Khanewal",
    "Layyah",
    "Bhakkar",
    "Chiniot",
    "Hafizabad",
    "Nankana Sahib",
    "Narowal",
    "Attock",
    "Chakwal",
    "Mianwali",
    "Bahawalnagar",
    "Pakpattan",
    "Lodhran",
    "Muzaffargarh",
    "Rajanpur",
    "Swat",
    "Mansehra",
    "Swabi",
    "Nowshera",
    "Kohat",
    "Bannu",
    "Hangu",
    "Haripur",
    "Charsadda",
    "Malakand",
    "Batkhela",
    "Gilgit",
    "Skardu",
    "Mirpur",
    "Muzaffarabad",
    "Kotli",
    "Bhimber",
    "Gwadar",
    "Turbat",
    "Khuzdar",
    "Sibi",
    "Hub",
    "Jacobabad",
    "Shikarpur",
    "Khairpur",
    "Nawabshah",
    "Sanghar",
    "Dadu",
    "Thatta",
    "Badin",
    "Tando Adam",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Umerkot",
    "Mirpur Khas"
)
